### ISSUE TITLE
VOLUME instruction causes trouble

### ISSUE THREAD

**Issue by joostmeijles** [sitecoreops/sitecore-images#22]
I am using Windows 10 update 1809 and Docker Desktop for Windows 2.0.0.3.

I start the system using a `docker-compose` file that overlays a bind-mount at the data directory location;
```
version: '2.4'

services:
 mssql:
  image: ...
  isolation: process
  environment:
    ACCEPT_EULA: "Y"
    sa_password: ${SQL_SA_PASSWORD}
  volumes:
    - .\data\mssql:C:\Data
```

With above setup I had following error:
- `ssql_1     | Invoke-Sqlcmd : Cannot detach the database` error when SQL server somehow was not properly shutdown (not killed)

This problem seem to be related to the `VOLUME` instruction in the Dockerfile (e.g. https://github.com/sitecoreops/sitecore-images/blob/5f35d9d2b4cbd35f4e7e5da6f07721b92f6ec813/images/9.0.2%20rev.%20180604/windowsservercore-ltsc2019/sitecore-sqldev/Dockerfile#L39)

When I remove the `VOLUME` instruction these problems (see https://github.com/avivasolutionsnl/sitecore-docker/pull/49) do no longer occur.

As there is no real added value for the `VOLUME` instruction in the Dockerfile, e.g. volume usage can be specified in the `docker-compose` file, I removed the instruction for the `avivasolutionsnl/sitecore-docker` repo.
